/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.1-49-g3e539d11e4-20220130"
#endif /* AVUTIL_FFVERSION_H */
