name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

defaults:
  run:
    working-directory: src



jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Check path
      run: echo ${{ github.workspace }} 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
        msbuild-architecture: x64
    - name: Build and restore
      run: msbuild -restore -p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ github.workspace }}\bin\Release\PiWeb.Volume.Tests.dll
